<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Foods\burger_beef.jpg" />
    <None Remove="Images\Foods\cocola.jpg" />
    <None Remove="Images\Foods\cocola.png" />
    <None Remove="Images\Foods\fries_large.jpg" />
    <None Remove="Images\Foods\pepsi.jpg" />
    <None Remove="Images\Foods\soda.jpg" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.21">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Images\Foods\burger_beef.jpg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Images\Foods\soda.jpg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Images\Foods\cocola.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Images\Foods\fries_large.jpg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Images\Foods\pepsi.jpg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
